name: wheelder
services:
- name: api
  github:
    repo: bafa2024/wheelder_platform
    branch: main
  build_command: pip install -r requirements.txt
  run_command: gunicorn wsgi:app
  http_port: 8080
  envs:
  - key: FLASK_ENV
    value: production
  - key: DEBUG
    value: "False"
  - key: PORT
    value: "8080"
  health_check:
    http_path: /
  log_destination:
    name: wheelder_logs
databases:
- name: wheelder_db
  engine: MYSQL
  version: "8"
  production: true
